# Generated in the build directory; source control never contains runtime bytes.
file(MAKE_DIRECTORY "${OUT}/bundle")
file(COPY "${ROOT}/engine/playground/nethack" DESTINATION "${OUT}/bundle")
execute_process(COMMAND "${STRIP}" "${OUT}/bundle/nethack" COMMAND_ERROR_IS_FATAL ANY)
set(files "${OUT}/bundle/nethack" "${OUT}/data/nhdat" "${OUT}/data/symbols" "${OUT}/data/license" "${OUT}/data/sysconf" "${ROOT}/NOTICE.md" "${ROOT}/build/LUA-LICENSE.txt")
set(names engine nhdat symbols license sysconf NOTICE.md LUA-LICENSE.txt)
# Dependency licenses are supplied by the static release builder.
if(DEFINED LICENSE_DIR AND NOT LICENSE_DIR STREQUAL "")
  file(GLOB licenses "${LICENSE_DIR}/*")
  foreach(path IN LISTS licenses)
    get_filename_component(name "${path}" NAME)
    list(APPEND files "${path}")
    list(APPEND names "${name}")
  endforeach()
endif()
set(code "/* Generated embedded runtime. */\n")
set(manifest "")
set(table "")
set(i 0)
foreach(path IN LISTS files)
  list(GET names ${i} name)
  file(SHA256 "${path}" hash)
  file(SIZE "${path}" size)
  string(APPEND manifest "${name}:${hash}\n")
  string(APPEND code "extern const unsigned char nnh_blob_${i}[];\n__asm__(\".pushsection .rodata\\n.balign 16\\n.global nnh_blob_${i}\\nnnh_blob_${i}:\\n.incbin \\\"${path}\\\"\\n.popsection\\n\");\n")
  if(i EQUAL 0)
    set(mode "0500")
  else()
    set(mode "0400")
  endif()
  string(APPEND table "{\"${name}\", nnh_blob_${i}, ${size}, ${mode}},\n")
  math(EXPR i "${i}+1")
endforeach()
string(SHA256 identity "${manifest}")
string(APPEND code "static const char bundle_id[] = \"${identity}\";\nstatic const struct bundle_file bundle_files[] = {\n${table}};\n")
file(WRITE "${OUT}/bundle/runtime.inc.new" "${code}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUT}/bundle/runtime.inc.new" "${OUT}/bundle/runtime.inc" COMMAND_ERROR_IS_FATAL ANY)
