import { catalog, requestSchema, type Schema } from "../protocol/catalog.ts";
import { responseSchema } from "../protocol/response.ts";
import { resolve } from "node:path";
import { readFile, writeFile } from "node:fs/promises";
const root = resolve(import.meta.dirname, "..");
function typeOf(s: Schema): string {
  if (s.oneOf) return s.oneOf.map(typeOf).join(" | ");
  if ("const" in s) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  if (s.type === "object") return `{ ${Object.entries(s.properties).map(([k, v]) => `${k}${s.required.includes(k) ? "" : "?"}: ${typeOf(v as Schema)}`).join("; ")} }`;
  if (s.type === "array") return `ReadonlyArray<${typeOf(s.items)}>`;
  return s.type === "integer" ? "number" : s.type;
}
const publicCatalog = { version: catalog.version, methods: catalog.methods.map(({ tool, action, ...method }) => method) };
const outputs: Record<string, string> = {
  "protocol/catalog.json": JSON.stringify(publicCatalog, null, 2) + "\n",
  "protocol/request.schema.json": JSON.stringify(requestSchema, null, 2) + "\n",
  "protocol/response.schema.json": JSON.stringify(responseSchema, null, 2) + "\n",
  "src/catalog.inc": "/* Generated by scripts/generate.ts; do not edit. */\nstatic const char nnh_catalog[] =\n" + JSON.stringify(JSON.stringify(catalog)) + ";\nstatic const char nnh_public_catalog[] =\n" + JSON.stringify(JSON.stringify(publicCatalog)) + ";\n",
  "typescript/requests.ts": "// Generated by scripts/generate.ts; do not edit.\nexport interface MethodParams {\n" + catalog.methods.map(m => `  ${JSON.stringify(m.name)}: ${typeOf(m.schema)};`).join("\n") + "\n}\nexport type Method = keyof MethodParams;\nexport type Request<M extends Method = Method> = { [K in M]: { version: 1; method: K; params: MethodParams[K] } }[M];\n",
};
const check = process.argv.includes("--check");
for (const [name, content] of Object.entries(outputs)) {
  const path = resolve(root, name);
  if (check) { if (await readFile(path, "utf8").catch(() => "") !== content) throw Error(`Stale generated file: ${name}`); }
  else await writeFile(path, content);
}
