import { compass, catalog, requestSchema, type Schema } from "../protocol/catalog.ts";
import { responseSchema, compactResponseSchema, hungerStates, burdenStates } from "../protocol/response.ts";
import { resolve } from "node:path";
import { readFile, writeFile } from "node:fs/promises";
const root = resolve(import.meta.dirname, "..");
function typeOf(s: Schema): string {
  if (s.oneOf) return s.oneOf.map(typeOf).join(" | ");
  if ("const" in s) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  if (s.type === "object") return `{ ${Object.entries(s.properties).map(([k, v]) => `${k}${s.required.includes(k) ? "" : "?"}: ${typeOf(v as Schema)}`).join("; ")} }`;
  if (s.type === "array") return `ReadonlyArray<${typeOf(s.items)}>`;
  return s.type === "integer" ? "number" : s.type;
}
const publicCatalog = { version: catalog.version, methods: catalog.methods.map(({ tool, action, ...method }) => method) };
const mcpTools = publicCatalog.methods.map(method => ({
  name: method.name.replaceAll('.', '_'),
  description: method.description + (method.name === 'session.observe' ? ' Returns the complete perceived state, including neighborhood/action offers, as a standalone snapshot. No baseline required. Other observations are deltas: replace supplied fields, upsert world by x,y; update.remove/worldRemoved delete fields/cells. Match update.base to last update.id. Query session.actions for neighborhood offers.' : ''),
  inputSchema: method.schema, outputSchema: compactResponseSchema,
  annotations: { readOnlyHint: method.readOnly === true, destructiveHint: method.readOnly !== true, idempotentHint: method.idempotent === true, openWorldHint: false },
}));
const outputs: Record<string, string> = {
  "typescript/self-state.ts": "// Generated by scripts/generate.ts; do not edit.\nexport type HungerState = " + hungerStates.map(s => JSON.stringify(s)).join(" | ") + ";\nexport type BurdenState = " + burdenStates.map(s => JSON.stringify(s)).join(" | ") + ";\n",
  "cli/mcp-tools.inc": "/* Generated by scripts/generate.ts; do not edit. */\nstatic const char mcp_tools[] = " + JSON.stringify(JSON.stringify({ tools: mcpTools })) + ";\n",
  "protocol/mcp-response.schema.json": JSON.stringify(compactResponseSchema, null, 2) + "\n",
  "mcp/protocol-data.ts": "// Generated by scripts/generate.ts; do not edit.\nexport const catalog = " + JSON.stringify(publicCatalog) + ";\nexport const responseSchema = " + JSON.stringify(responseSchema) + ";\nexport const compactResponseSchema = " + JSON.stringify(compactResponseSchema) + ";\n",
  "protocol/catalog.json": JSON.stringify(publicCatalog, null, 2) + "\n",
  "protocol/request.schema.json": JSON.stringify(requestSchema, null, 2) + "\n",
  "protocol/response.schema.json": JSON.stringify(responseSchema, null, 2) + "\n",
  "src/catalog.inc": "/* Generated by scripts/generate.ts; do not edit. */\nstatic const char nnh_catalog[] =\n" + JSON.stringify(JSON.stringify(catalog)) + ";\nstatic const char nnh_public_catalog[] =\n" + JSON.stringify(JSON.stringify(publicCatalog)) + ";\n",
  "typescript/requests.ts": "// Generated by scripts/generate.ts; do not edit.\nexport interface MethodParams {\n" + catalog.methods.map(m => `  ${JSON.stringify(m.name)}: ${typeOf(m.schema)};`).join("\n") + "\n}\nexport type Method = keyof MethodParams;\nexport type Request<M extends Method = Method> = { [K in M]: { version: 1; method: K; params: MethodParams[K] } }[M];\n",
};
// Species vocabulary contains displayed names only, never private monster stats.
const monsterSource = await readFile(resolve(root, "engine/include/monsters.h"), "utf8");
const names = [...monsterSource.matchAll(/MON\(\s*(?:NAM\("([^"]+)"\)|NAMS\("[^"]+",\s*"[^"]+",\s*"([^"]+)"\))/g)].map(m => m[1] ?? m[2]!);
if (names.length < 300) throw Error("Monster name vocabulary is incomplete");
const members = new Map<string, string>();
for (const name of names) {
  const key = name.split(/[^a-zA-Z0-9]+/).map(w => w[0]?.toUpperCase() + w.slice(1)).join("");
  if (members.has(key) && members.get(key) !== name) throw Error("Duplicate entity name: " + key);
  members.set(key, name);
}
const directionNames = ["north", "northEast", "east", "southEast", "south", "southWest", "west", "northWest"];
outputs["typescript/vocabulary.ts"] = "// Generated by scripts/generate.ts; do not edit.\n"
  + "/** Compass directions accepted by the public engine. */\nexport enum direction {\n"
  + compass.enum.map((v: string, i: number) => "  " + directionNames[i] + " = " + JSON.stringify(v) + ",").join("\n") + "\n}\n"
  + "/** Filters and perceived species names. Appearance does not reveal hidden identity. */\nexport enum entities {\n  Enemy = \"@enemy\",\n  Creature = \"@creature\",\n  Ally = \"@ally\",\n  Peaceful = \"@peaceful\",\n"
  + [...members].map(([key, name]) => "  " + key + " = " + JSON.stringify(name) + ",").join("\n") + "\n}\n";
const check = process.argv.includes("--check");
for (const [name, content] of Object.entries(outputs)) {
  const path = resolve(root, name);
  if (check) { if (await readFile(path, "utf8").catch(() => "") !== content) throw Error(`Stale generated file: ${name}`); }
  else await writeFile(path, content);
}
