import { encounterArt, type CreaturePixels } from "./encounter-art";
import { earlyCreatures } from "./creature-presets";
import { monsterAppearances } from "./monster-appearances";

export type CreatureRecipe = {
  family: string;
  size: "small" | "medium" | "large";
  palette: string;
  asset?: "dog" | "cat" | "bat";
};
export const creaturePalettes: Record<
  string,
  { body: string; shade: string; highlight: string }
> = {
  earth: { body: "#b49570", shade: "#6f5743", highlight: "#e5cfac" },
  sage: { body: "#9cad78", shade: "#526c55", highlight: "#d9dbac" },
  clay: { body: "#bb7866", shade: "#714f4a", highlight: "#e5bd99" },
  mist: { body: "#83acb6", shade: "#526f84", highlight: "#d3e1d7" },
  slate: { body: "#939daa", shade: "#555e70", highlight: "#d7d7d2" },
  ivory: { body: "#d9d5b9", shade: "#92927c", highlight: "#f1ead2" },
  ink: { body: "#657080", shade: "#394551", highlight: "#a3b1ba" },
  amber: { body: "#c4aa61", shade: "#817046", highlight: "#ecd99f" },
  plum: { body: "#ae8aa9", shade: "#6c576e", highlight: "#dfbdce" },
};
const rows = (...pixels: string[]) =>
  pixels.map((row) =>
    row.padEnd(Math.max(...pixels.map((r) => r.length)), "."),
  );
/** Original family masters. Native-pixel sizes, fixed foot anchor; no CSS filters
 * or engine size/strength values. Existing small encounters remain exact presets. */
export const creatureBases: Record<string, string[]> = {
  ant: encounterArt["giant ant"]!.pixels,
  bee: encounterArt["killer bee"]!.pixels,
  spider: encounterArt["cave spider"]!.pixels,
  lizard: encounterArt.gecko!.pixels,
  snake: encounterArt["garter snake"]!.pixels,
  canine: encounterArt.coyote!.pixels,
  eye: encounterArt["floating eye"]!.pixels,
  spore: encounterArt["gas spore"]!.pixels,
  slime: encounterArt["acid blob"]!.pixels,
  fungus: encounterArt["brown mold"]!.pixels,
  humanoid: rows(
    "......ssss......",
    ".....s####s.....",
    ".....#hhhh#.....",
    ".....#h#h##.....",
    "......#hh#......",
    "....###ss###....",
    "...#hsoooosh#...",
    "...#hsoooosh#...",
    "...#ssooooss#...",
    "....#oooooo#....",
    "....#oooooo#....",
    "....#ssssss#....",
    ".....#ss#s#.....",
    ".....#ss#s#.....",
    ".....#hs#h#.....",
    ".....###.##.....",
  ),
  goblin: earlyCreatures.goblin!.pixels,
  rodent: earlyCreatures["giant rat"]!.pixels,
  bird: rows(
    "......###......",
    ".....#hho##....",
    ".....#o#oos#...",
    "......#oo##....",
    ".....#hoo#.....",
    "...##hooo##....",
    "..#hhoooss#....",
    ".#hhooosss#....",
    "..###oosss#....",
    ".....#ss##.....",
    ".....#s#s#.....",
    "....##..##.....",
  ),
  feline: rows(
    ".........#..#...",
    "........#h##s#..",
    "........#hoos#..",
    ".........#o#o##.",
    "......###hooss#.",
    "..####hhoooo##..",
    ".#hhoooooosss#..",
    "#ss#ooooossss#..",
    "#s..#os#ss#os#..",
    ".#..#ss#..#ss#..",
    "....###...###...",
  ),
  bat: rows(
    "#..............#",
    "#h#..........#h#",
    "#hm#..#..#..#mh#",
    ".##m##h##h##m##.",
    "..#hmhhoooomh#..",
    "...##ooooss##...",
    ".....#o##o#.....",
    "......#ss#......",
    ".......##.......",
  ),
  mimic: rows(
    "..############..",
    ".#hhooooooooss#.",
    "#hhooooooooooss#",
    "#hhooooooooooss#",
    "################",
    "#ss##h##h##h#ss#",
    "#hoos#ss#ss#oos#",
    "#hooo######ooss#",
    ".##oossssssos##.",
    "...##ssssss##...",
    "..#os##..##so#..",
    "...##......##...",
  ),
  piercer: rows(
    ".......##.......",
    "......#hh#......",
    "......#hos#.....",
    ".....#hoos#.....",
    ".....#hooos#....",
    "....#hoooos#....",
    "....#hooosos#...",
    "...#hooossss#...",
    "..#hooossoss#...",
    "...#oo#oo#oo#...",
    "....##.##.##....",
  ),
  quadruped: rows(
    "...........######...",
    "..........#hhoooo##.",
    ".........#hoo#oooos#",
    "....#####hoooooooss#",
    "..##hhooooooossssss#",
    ".#hhooooooooooss###.",
    "#hooooooooosssss#...",
    "#hooooooooosssss#...",
    ".#ooooosssosssss#...",
    "..#oss#ss#ss#oss#...",
    "..#oss#..#ss#oss#...",
    "..####...###.###....",
  ),
  carpet: rows(
    "..###.######.###..",
    ".#hh###hhhh###hh#.",
    "#hhooooooooosooos#",
    "#hooosoooooossoss#",
    "#hooossoosoooooss#",
    "#hooooossssooosss#",
    ".##ssssssssssss##.",
    "...###.####.###...",
  ),
  horse: rows(
    ".............##....",
    "............#hh#...",
    "...........#hoo##..",
    "...........#h#oos#.",
    "..........#hooos##.",
    "....######hooos#...",
    "..##hhoooooooos#...",
    ".#hhoooooooooss#...",
    "#s#oooooooossss#...",
    "#s.#ossssssoss#....",
    ".#.#os#...#os#.....",
    "...#os#...#os#.....",
    "...#ss#...#ss#.....",
    "...####...####.....",
  ),
  vortex: rows(
    ".....######.....",
    "...##hhhhss##...",
    "..#hoo####oss#..",
    ".#ho##....#oss#.",
    ".#hs#..##..#os#.",
    "..#s#.#ho#.#ss#.",
    "...#..#os##ss#..",
    "..#h#..#ssss#...",
    "...#ho######....",
    "....#hoooss#....",
    ".....#hoss#.....",
    "......####......",
  ),
  worm: rows(
    "...........####...",
    "..........#hhoos#.",
    "..........#o#ooss#",
    "...####...#hoooss#",
    "..#hhoos#..#oooss#",
    ".#hhoooos###ooss#.",
    "#hooossssooooos#..",
    "#oss####ssssss#...",
    ".###....######....",
  ),
  orb: rows(
    ".....####.....",
    "...##hhhh##...",
    "..#hhooooos#..",
    ".#hhooooooss#.",
    ".#hooohoooss#.",
    ".#hooooossss#.",
    "..#oossssss#..",
    "...##ssss##...",
    ".....####.....",
  ),
  ape: rows(
    "......######......",
    "....##hhoooo##....",
    "...#hoooooooss#...",
    "...#hoo#oo#oss#...",
    "....#hhhhhoss#....",
    "..###hhssssss###..",
    ".#hhooooooooosss#.",
    "#hhooooooooosssss#",
    "#hoosooooooossos#",
    "#hos#ooooooss#oss#",
    "#ss#.#######.#sss#",
    ".##..#ossoss#..##.",
    ".....#os##os#.....",
    "....#oss##oss#....",
    "....####..####....",
  ),
  winged: rows(
    "#.......####.......#",
    "#h#....#hhhh#....#h#",
    "#hm#...#h#hh#...#mh#",
    "#hmm#...#hh#...#mmh#",
    ".##mm###hss###mm##.",
    "..#hmmhoooooohmmh#..",
    "...##hsooooosh##....",
    "....#hsooooosh#.....",
    ".....#oooooo#.......",
    ".....#oooooo#.......",
    "....#ooooooss#......",
    "....#ooooooss#......",
    "...#ooooooosss#.....",
    "...############.....",
  ),
  centaur: rows(
    "...........####.....",
    "..........#hhhh#....",
    "..........#h#hh#....",
    "...........#hh#.....",
    ".........##ssss##...",
    "........#hsoooosh#..",
    "........#hooooosh#..",
    "....#####oooooss#...",
    "..##hhooooooooos#...",
    ".#hhooooooooooos#...",
    "#s#ooooooooossss#...",
    "#s.#oss#ss#oss#.....",
    ".#.#oss#..#oss#.....",
    "...#oss#..#oss#.....",
    "...####...####......",
  ),
  dragon: rows(
    "#.............#...#.....",
    "#h#..........#h###s#....",
    "#hm#........#hhoooos##..",
    "#hmm#.......#ho#ooosss#.",
    "#hmmm#.......#hoooss##..",
    ".##mmm###...#hooss##....",
    "..#hmmmoo###hooss#......",
    "...#hmmhoooooooss#......",
    "...#hhoooooooooss#......",
    "..#hhooooooooosss#......",
    ".#hhooooooooossss#...##.",
    "#ss#ooooossoossss#..#os#",
    "#s..#oss##ss#oss####ss#.",
    ".#..#oss#...#ossoss##...",
    "....####....#######.....",
  ),
  giant: rows(
    "......######......",
    ".....#hhoooo#.....",
    ".....#ho#o#s#.....",
    ".....#hhooss#.....",
    "......#hhss#......",
    "...###ssssss###...",
    "..#hhooooooooos#..",
    ".#hhooooooooooss#.",
    ".#hooosooooososs#.",
    ".#hos#oooooss#os#.",
    ".#oss#oooooss#os#.",
    "..###.##########..",
    "......#oooss#.....",
    ".....#oossoos#....",
    ".....#oss#oss#....",
    ".....#oss#oss#....",
    "....#ssss#ssss#...",
    "....#####.#####...",
  ),
  robed: rows(
    "......####......",
    ".....#hhhh#.....",
    "....#hssssm#....",
    "...#hs####sm#...",
    "...#hs#hh#sm#...",
    "....#s#h##s#....",
    ".....##ss##.....",
    "....#hoooos#....",
    "...#hhooooss#...",
    "...#hoooooss#...",
    "..#hhooooosss#..",
    "..#hoooooosss#..",
    ".#hhooooooosss#.",
    ".#hooooooossss#.",
    "..############..",
  ),
  mummy: rows(
    ".....######.....",
    "....#hhsshh#....",
    "....#sshhhh#....",
    "....#hh#h#s#....",
    ".....#sshh#.....",
    "...###hhss###...",
    "..#hhsshhooss#..",
    "..#sshhoosshh#..",
    "...##hhssoo##...",
    "....#sshhhss#...",
    "....#hhsshhh#...",
    "....#sshhsso#...",
    ".....#hh#ss#....",
    ".....#ss#hh#....",
    "....#hhh#sss#...",
    "....####.####...",
  ),
  naga: rows(
    ".......####.....",
    "......#hhoo#....",
    ".....#hoo#os#...",
    ".....#hhooos#...",
    "......##oos#....",
    ".......#hos#....",
    "......#hoos#....",
    "......#hoos#....",
    ".....#hooos#....",
    "....#hoooos#....",
    "..###hoooos###..",
    ".#hhooossssoss#.",
    "#hooss####ssoss#",
    ".##hhoooosss##..",
    "...#########....",
  ),
  beetle: rows(
    "....##......##....",
    "...#ho#....#oh#...",
    "....#ho####os#....",
    "....#hhooooss#....",
    "..###hoo#ooss###..",
    ".#s#hooooooos#s#..",
    "..##hhoo#ooss##...",
    ".#s#hooossssss#s#.",
    "#s..#hoosssss#..s#",
    ".#..#ooossoss#..#.",
    "...#s#######ss#...",
    "..##.........##...",
  ),
  tripod: rows(
    ".......####.......",
    ".....##hhoo##.....",
    "....#hhooooos#....",
    "...#ho#oo#ooss#...",
    "..#hhooooooosss#..",
    "..#hoo######oss#..",
    "..#hoo#hhhh#oss#..",
    "...#oosssssoss#...",
    "....#ooosssss#....",
    "...#oss#oss#oss#..",
    "..#oss#.#ss#.#ss#.",
    "..####..###..####.",
  ),
  shambler: rows(
    "......####......",
    ".....#hhoo#.....",
    ".....#h#os#.....",
    "......#oss#.....",
    "..####ssos###...",
    ".#hhoooooooss#..",
    ".#s#oooooosss#..",
    ".#s#ooossss#ss#.",
    "..#.#ooosss#.##.",
    "....#ssssss#....",
    "....#ossoss#....",
    "....#oss#os#....",
    ".....#ss#oss#...",
    "....####.####...",
  ),
  golem: rows(
    ".....########.....",
    "....#hhhhooos#....",
    "....#hho#o#ss#....",
    "....#hhooooss#....",
    ".....###ss###.....",
    "...##hhooooss##...",
    "..#hhooooooooss#..",
    "..#hoooooooooss#..",
    "..#hosooooossos#..",
    "..#hosooooossos#..",
    "..#sss######sss#..",
    "...###ooosss###...",
    ".....#oo#oss#.....",
    ".....#oo#oss#.....",
    "....#sss#ssss#....",
    "....####.#####....",
  ),
  ghost: rows(
    ".....######.....",
    "....#hhhhhhs#...",
    "...#hhhooooss#..",
    "...#h##oo##ss#..",
    "...#hooooosss#..",
    "....#hooosss#...",
    "....#hooosss#...",
    "...#hhoooosss#..",
    "..#hhhooooosss#.",
    ".#hhhooooooosss#",
    "..##oosssooss##.",
    "....#ss##ss##...",
    ".....##..##.....",
  ),
  demon: rows(
    "....#........#....",
    "...#h#......#s#...",
    "...#ho######os#...",
    "....#hhooooss#....",
    "...#hoo#oo#oss#...",
    "#...#hhooooss#...#",
    "#h###hhooooss###s#",
    ".##hhooooooooos##.",
    "..#hoooossooooss#.",
    "..#hosoooooss#os#.",
    "..#hosoooooss#os#.",
    "...###ooooosss##..",
    ".....#oossoss#....",
    ".....#oss#oss#....",
    "....#ssss#ssss#...",
    "....#####.#####...",
  ),
  fish: rows(
    "............#....",
    ".....######.##...",
    "...##hhoooo#os#..",
    "..#hhooo#oooss#..",
    ".#hhooooooooss#..",
    "..#ooossssssos#..",
    "...##ssssss#.##..",
    ".....######..#...",
  ),
  cube: rows(
    "..############..",
    ".#hhhhhhhhhhhs#.",
    "#hhooooooooosss#",
    "#hooooooooososs#",
    "#hoosooooossoos#",
    "#hooosooosoooos#",
    "#hoooossoooooss#",
    "#hooooosooossss#",
    ".##############.",
  ),
  scorpion: rows(
    ".............###..",
    "............#hos#.",
    "...........#hos#..",
    "...#...#...#oss#..",
    "..#h#.#h#...#os#..",
    "...#h#ho#..#oss#..",
    "....#hoo###oss#...",
    "..###hooooooss#...",
    ".#s#hoosssssss#...",
    "..#s#ss##ss#ss#...",
    "...#..#..#..#.....",
  ),
  jellyfish: rows(
    ".....######.....",
    "...##hhhhhh##...",
    "..#hhooooooss#..",
    ".#hoooooooosss#.",
    "..############..",
    "...#os#os#os#...",
    "...#os#os#os#...",
    "....#s#os#s#....",
    ".....##os##.....",
    ".......##.......",
  ),
  skeleton: rows(
    "......####......",
    ".....#hhhh#.....",
    ".....#h##h#.....",
    "......#hh#......",
    "......#ss#......",
    "...###hssh###...",
    "..#h#hhsshh#h#..",
    "..#h#.hssh.#h#..",
    "...#..hssh..#...",
    "......#hh#......",
    ".....#h##h#.....",
    ".....#h##h#.....",
    ".....#h#.#h#....",
    "....###..###....",
  ),
  tentacled: rows(
    "......######......",
    ".....#hhoooo#.....",
    "....#hhooooos#....",
    "....#hoo#o#ss#....",
    ".....#ooooos#.....",
    "....#ho#os#os#....",
    "....#os#os#os#....",
    ".....#s#ss#s#.....",
    "....##osssos##....",
    "...#hhooooosss#...",
    "...#hoooooooss#...",
    "..#hhooooooosss#..",
    "...############...",
  ),
  elemental: rows(
    "........#.........",
    ".......#h#........",
    "...#..#hoo#.......",
    "..#h##hooos#..#...",
    "..#hhoooooss##h#..",
    "...#hooooooooss#..",
    "..#hhoooooooooss#.",
    ".#hhooooooosoosss#",
    "..#hoooossssoss##.",
    "...#hoossssss##...",
    "..#hhoosssssss#...",
    "...#ssssssssss#...",
    "....##########....",
  ),
};

const cache = new Map<string, CreaturePixels>();
export function creatureRecipe(
  appearance?: string,
): CreatureRecipe | undefined {
  return appearance && Object.hasOwn(monsterAppearances, appearance)
    ? monsterAppearances[appearance]
    : undefined;
}
export function companionAsset(appearance?: string) {
  return creatureRecipe(appearance)?.asset;
}
export function knownCreatureArt(appearance?: string) {
  return Boolean(creatureRecipe(appearance));
}
/** Deterministic native-pixel resampling, compiled once per shared recipe. These
 * sizes express art direction, not the engine's MZ size, threat or level. */
export function familyPixels(recipe: CreatureRecipe): CreaturePixels {
  const key = recipe.family + "." + recipe.size + "." + recipe.palette;
  const found = cache.get(key);
  if (found) return found;
  const base = creatureBases[recipe.family],
    palette = creaturePalettes[recipe.palette];
  if (!base || !palette) throw Error("Invalid creature art recipe " + key);
  const factor =
    recipe.size === "small" ? 0.75 : recipe.size === "large" ? 1.35 : 1;
  const width = Math.min(26, Math.max(6, Math.round(base[0]!.length * factor)));
  const height = Math.min(26, Math.max(5, Math.round(base.length * factor)));
  const pixels = Array.from({ length: height }, (_, y) =>
    Array.from(
      { length: width },
      (_, x) =>
        base[
          Math.min(base.length - 1, Math.floor((y * base.length) / height))
        ]![
          Math.min(
            base[0]!.length - 1,
            Math.floor((x * base[0]!.length) / width),
          )
        ]!,
    ).join(""),
  );
  // Some masters use m for the same midtone as o.
  const art = {
    ...palette,
    pixels: pixels.map((row) => row.replaceAll("m", "o")),
  };
  cache.set(key, art);
  return art;
}
export function creaturePixels(
  appearance?: string,
): CreaturePixels | undefined {
  const recipe = creatureRecipe(appearance);
  if (!recipe || recipe.asset) return;
  return (
    earlyCreatures[appearance!] ??
    encounterArt[appearance!] ??
    familyPixels(recipe)
  );
}
