import type { CreaturePixels } from "./encounter-art";
// Original editable creature pixels, independent of the private asset packs.
// The engine's apparent species selects art; glyph/color never supplies identity.
export const earlyCreatures: Record<string, CreaturePixels> = {
  newt: {
    body: "#c1a66d",
    shade: "#76623e",
    pixels: [
      "......###.",
      ".....#hoo#",
      "..###oo#o#",
      ".#hhooos#.",
      "#ss#os#...",
      ".##.##....",
    ],
  },
  jackal: {
    body: "#c09461",
    shade: "#79573d",
    pixels: [
      "..##...##...",
      "..#h#.#oh#..",
      "..#hh#hoo#..",
      "..#hhoooo#..",
      "..#o#oo#o#..",
      "...#hhoss#..",
      "...#oo#ss#..",
      "..#hooss#...",
      ".#hooooos#..",
      ".#ooossss#..",
      "..#os#os#...",
      "..###.###...",
    ],
  },
  lichen: {
    body: "#9dac65",
    shade: "#536a4b",
    pixels: [
      "...###...",
      ".##hoo##.",
      "#hhooooh#",
      "#ooossoo#",
      ".#ssssss#",
      "..######.",
    ],
  },
  goblin: {
    body: "#91a76d",
    shade: "#4c6450",
    pixels: [
      "....####....",
      "...#hhho#...",
      "###hhoos###.",
      "#oo#o#o#oo#.",
      ".###oho###..",
      "...#ohhs#...",
      "..##ssss##..",
      ".#hsoooosh#.",
      ".#osssssso#.",
      "..#ooooss#..",
      "..#ss##ss#..",
      "..###..###..",
    ],
  },
  kobold: {
    body: "#b38b63",
    shade: "#725a43",
    pixels: [
      "....###.....",
      "...#hho#....",
      "..#hhoos#...",
      "..#o#o#os#..",
      "...#hhooos#.",
      "...#oo####..",
      "..##ssss#...",
      ".#hhoooos#..",
      ".#sooooos#..",
      "..#osssos#..",
      "..#os##os#..",
      "..###..###..",
    ],
  },
  "sewer rat": {
    body: "#a58a78",
    shade: "#655b57",
    pixels: [
      "....##....",
      "..##ho###.",
      ".#hoooo#o#",
      "#sssssoss#",
      "#..##.##..",
    ],
  },
  "giant rat": {
    body: "#a99b83",
    shade: "#6f6759",
    pixels: [
      "............",
      "....##..##..",
      "...#hh##hh#.",
      "...#hoooos#.",
      "..#hho#o#ss#",
      "..#hoooooss#",
      "..#hoooo#ss#",
      ".#hoooooos#.",
      "#.#ossss##..",
      "#..#s##s#...",
      ".##.........",
      "............",
    ],
  },
};
