/** Generated by scripts/generate-monster-art.mjs from the pinned source.
 * Appearance lookup only: no hidden IDs, combat data, ranks or spawn tables.
 * Ambiguous names deliberately have no recipe; never resolve them from glyphs. */
import type {CreatureRecipe} from "./creature-families";
export const monsterAppearances: Readonly<Record<string, CreatureRecipe>> = {
  "giant ant": {
    "family": "ant",
    "size": "large",
    "palette": "earth"
  },
  "killer bee": {
    "family": "bee",
    "size": "small",
    "palette": "earth"
  },
  "soldier ant": {
    "family": "ant",
    "size": "small",
    "palette": "earth"
  },
  "fire ant": {
    "family": "ant",
    "size": "small",
    "palette": "earth"
  },
  "giant beetle": {
    "family": "beetle",
    "size": "large",
    "palette": "earth"
  },
  "queen bee": {
    "family": "bee",
    "size": "small",
    "palette": "earth"
  },
  "acid blob": {
    "family": "slime",
    "size": "small",
    "palette": "sage"
  },
  "quivering blob": {
    "family": "slime",
    "size": "small",
    "palette": "sage"
  },
  "gelatinous cube": {
    "family": "cube",
    "size": "small",
    "palette": "sage"
  },
  "chickatrice": {
    "family": "bird",
    "size": "small",
    "palette": "earth"
  },
  "cockatrice": {
    "family": "bird",
    "size": "small",
    "palette": "earth"
  },
  "pyrolisk": {
    "family": "bird",
    "size": "small",
    "palette": "earth"
  },
  "jackal": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "fox": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "coyote": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "little dog": {
    "family": "canine",
    "size": "small",
    "palette": "earth",
    "asset": "dog"
  },
  "dingo": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "dog": {
    "family": "canine",
    "size": "medium",
    "palette": "earth",
    "asset": "dog"
  },
  "large dog": {
    "family": "canine",
    "size": "large",
    "palette": "earth",
    "asset": "dog"
  },
  "wolf": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "winter wolf cub": {
    "family": "canine",
    "size": "small",
    "palette": "earth"
  },
  "warg": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "winter wolf": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "hell hound pup": {
    "family": "canine",
    "size": "small",
    "palette": "earth"
  },
  "hell hound": {
    "family": "canine",
    "size": "medium",
    "palette": "earth"
  },
  "gas spore": {
    "family": "spore",
    "size": "small",
    "palette": "mist"
  },
  "floating eye": {
    "family": "eye",
    "size": "small",
    "palette": "mist"
  },
  "freezing sphere": {
    "family": "orb",
    "size": "small",
    "palette": "mist"
  },
  "flaming sphere": {
    "family": "orb",
    "size": "small",
    "palette": "mist"
  },
  "shocking sphere": {
    "family": "orb",
    "size": "small",
    "palette": "mist"
  },
  "kitten": {
    "family": "feline",
    "size": "small",
    "palette": "earth",
    "asset": "cat"
  },
  "housecat": {
    "family": "feline",
    "size": "medium",
    "palette": "earth",
    "asset": "cat"
  },
  "jaguar": {
    "family": "feline",
    "size": "medium",
    "palette": "earth"
  },
  "lynx": {
    "family": "feline",
    "size": "medium",
    "palette": "earth"
  },
  "panther": {
    "family": "feline",
    "size": "medium",
    "palette": "earth"
  },
  "large cat": {
    "family": "feline",
    "size": "large",
    "palette": "earth",
    "asset": "cat"
  },
  "tiger": {
    "family": "feline",
    "size": "medium",
    "palette": "earth"
  },
  "displacer beast": {
    "family": "feline",
    "size": "medium",
    "palette": "earth"
  },
  "gremlin": {
    "family": "goblin",
    "size": "small",
    "palette": "slate"
  },
  "gargoyle": {
    "family": "winged",
    "size": "medium",
    "palette": "slate"
  },
  "winged gargoyle": {
    "family": "winged",
    "size": "small",
    "palette": "slate"
  },
  "hobbit": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "bugbear": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf lord": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf lady": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf leader": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf king": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf queen": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "dwarf ruler": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "mind flayer": {
    "family": "tentacled",
    "size": "medium",
    "palette": "earth"
  },
  "master mind flayer": {
    "family": "tentacled",
    "size": "medium",
    "palette": "earth"
  },
  "manes": {
    "family": "goblin",
    "size": "small",
    "palette": "clay"
  },
  "homunculus": {
    "family": "goblin",
    "size": "small",
    "palette": "clay"
  },
  "imp": {
    "family": "goblin",
    "size": "small",
    "palette": "clay"
  },
  "lemure": {
    "family": "goblin",
    "size": "small",
    "palette": "clay"
  },
  "quasit": {
    "family": "goblin",
    "size": "small",
    "palette": "clay"
  },
  "tengu": {
    "family": "goblin",
    "size": "small",
    "palette": "clay"
  },
  "blue jelly": {
    "family": "slime",
    "size": "small",
    "palette": "mist"
  },
  "spotted jelly": {
    "family": "slime",
    "size": "small",
    "palette": "mist"
  },
  "ochre jelly": {
    "family": "slime",
    "size": "small",
    "palette": "mist"
  },
  "kobold": {
    "family": "goblin",
    "size": "small",
    "palette": "earth"
  },
  "large kobold": {
    "family": "goblin",
    "size": "large",
    "palette": "earth"
  },
  "kobold lord": {
    "family": "goblin",
    "size": "small",
    "palette": "earth"
  },
  "kobold lady": {
    "family": "goblin",
    "size": "small",
    "palette": "earth"
  },
  "kobold leader": {
    "family": "goblin",
    "size": "small",
    "palette": "earth"
  },
  "kobold shaman": {
    "family": "goblin",
    "size": "small",
    "palette": "earth"
  },
  "leprechaun": {
    "family": "humanoid",
    "size": "small",
    "palette": "sage"
  },
  "small mimic": {
    "family": "mimic",
    "size": "small",
    "palette": "earth"
  },
  "large mimic": {
    "family": "mimic",
    "size": "large",
    "palette": "earth"
  },
  "giant mimic": {
    "family": "mimic",
    "size": "large",
    "palette": "earth"
  },
  "wood nymph": {
    "family": "humanoid",
    "size": "medium",
    "palette": "sage"
  },
  "water nymph": {
    "family": "humanoid",
    "size": "medium",
    "palette": "sage"
  },
  "mountain nymph": {
    "family": "humanoid",
    "size": "medium",
    "palette": "sage"
  },
  "goblin": {
    "family": "goblin",
    "size": "small",
    "palette": "sage"
  },
  "hobgoblin": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "orc": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "hill orc": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "Mordor orc": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "Uruk-hai": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "orc shaman": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "orc-captain": {
    "family": "goblin",
    "size": "large",
    "palette": "sage"
  },
  "rock piercer": {
    "family": "piercer",
    "size": "small",
    "palette": "slate"
  },
  "iron piercer": {
    "family": "piercer",
    "size": "small",
    "palette": "slate"
  },
  "glass piercer": {
    "family": "piercer",
    "size": "small",
    "palette": "slate"
  },
  "rothe": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "mumak": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "leocrotta": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "wumpus": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "titanothere": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "baluchitherium": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "mastodon": {
    "family": "quadruped",
    "size": "large",
    "palette": "earth"
  },
  "sewer rat": {
    "family": "rodent",
    "size": "small",
    "palette": "earth"
  },
  "giant rat": {
    "family": "rodent",
    "size": "large",
    "palette": "earth"
  },
  "rabid rat": {
    "family": "rodent",
    "size": "small",
    "palette": "earth"
  },
  "rock mole": {
    "family": "rodent",
    "size": "small",
    "palette": "earth"
  },
  "woodchuck": {
    "family": "rodent",
    "size": "small",
    "palette": "earth"
  },
  "cave spider": {
    "family": "spider",
    "size": "small",
    "palette": "earth"
  },
  "centipede": {
    "family": "worm",
    "size": "small",
    "palette": "earth"
  },
  "giant spider": {
    "family": "spider",
    "size": "large",
    "palette": "earth"
  },
  "scorpion": {
    "family": "scorpion",
    "size": "small",
    "palette": "earth"
  },
  "lurker above": {
    "family": "carpet",
    "size": "large",
    "palette": "slate"
  },
  "trapper": {
    "family": "carpet",
    "size": "large",
    "palette": "slate"
  },
  "pony": {
    "family": "horse",
    "size": "small",
    "palette": "earth"
  },
  "white unicorn": {
    "family": "horse",
    "size": "large",
    "palette": "ivory"
  },
  "gray unicorn": {
    "family": "horse",
    "size": "large",
    "palette": "slate"
  },
  "black unicorn": {
    "family": "horse",
    "size": "large",
    "palette": "ink"
  },
  "horse": {
    "family": "horse",
    "size": "medium",
    "palette": "earth"
  },
  "warhorse": {
    "family": "horse",
    "size": "large",
    "palette": "earth"
  },
  "fog cloud": {
    "family": "vortex",
    "size": "medium",
    "palette": "mist"
  },
  "dust vortex": {
    "family": "vortex",
    "size": "medium",
    "palette": "mist"
  },
  "ice vortex": {
    "family": "vortex",
    "size": "medium",
    "palette": "mist"
  },
  "energy vortex": {
    "family": "vortex",
    "size": "medium",
    "palette": "mist"
  },
  "steam vortex": {
    "family": "vortex",
    "size": "medium",
    "palette": "mist"
  },
  "fire vortex": {
    "family": "vortex",
    "size": "medium",
    "palette": "mist"
  },
  "baby long worm": {
    "family": "worm",
    "size": "small",
    "palette": "earth"
  },
  "baby purple worm": {
    "family": "worm",
    "size": "small",
    "palette": "plum"
  },
  "long worm": {
    "family": "worm",
    "size": "large",
    "palette": "earth"
  },
  "purple worm": {
    "family": "worm",
    "size": "large",
    "palette": "plum"
  },
  "grid bug": {
    "family": "ant",
    "size": "small",
    "palette": "sage"
  },
  "xan": {
    "family": "ant",
    "size": "small",
    "palette": "sage"
  },
  "yellow light": {
    "family": "orb",
    "size": "small",
    "palette": "amber"
  },
  "black light": {
    "family": "orb",
    "size": "small",
    "palette": "ink"
  },
  "zruty": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "couatl": {
    "family": "naga",
    "size": "large",
    "palette": "ivory"
  },
  "Aleax": {
    "family": "winged",
    "size": "large",
    "palette": "ivory"
  },
  "Angel": {
    "family": "winged",
    "size": "large",
    "palette": "ivory"
  },
  "ki-rin": {
    "family": "horse",
    "size": "large",
    "palette": "ivory"
  },
  "Archon": {
    "family": "winged",
    "size": "large",
    "palette": "ivory"
  },
  "bat": {
    "family": "bat",
    "size": "small",
    "palette": "slate",
    "asset": "bat"
  },
  "giant bat": {
    "family": "bat",
    "size": "large",
    "palette": "slate"
  },
  "raven": {
    "family": "bird",
    "size": "small",
    "palette": "slate"
  },
  "vampire bat": {
    "family": "bat",
    "size": "small",
    "palette": "slate"
  },
  "plains centaur": {
    "family": "centaur",
    "size": "large",
    "palette": "earth"
  },
  "forest centaur": {
    "family": "centaur",
    "size": "large",
    "palette": "earth"
  },
  "mountain centaur": {
    "family": "centaur",
    "size": "large",
    "palette": "earth"
  },
  "baby gray dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "slate"
  },
  "baby gold dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "amber"
  },
  "baby silver dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "ivory"
  },
  "baby red dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "clay"
  },
  "baby white dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "ivory"
  },
  "baby orange dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "clay"
  },
  "baby black dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "ink"
  },
  "baby blue dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "mist"
  },
  "baby green dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "sage"
  },
  "baby yellow dragon": {
    "family": "dragon",
    "size": "small",
    "palette": "amber"
  },
  "gray dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "slate"
  },
  "gold dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "amber"
  },
  "silver dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "ivory"
  },
  "red dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "clay"
  },
  "white dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "ivory"
  },
  "orange dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "clay"
  },
  "black dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "ink"
  },
  "blue dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "mist"
  },
  "green dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "sage"
  },
  "yellow dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "amber"
  },
  "stalker": {
    "family": "ghost",
    "size": "large",
    "palette": "slate"
  },
  "air elemental": {
    "family": "vortex",
    "size": "large",
    "palette": "slate"
  },
  "fire elemental": {
    "family": "elemental",
    "size": "large",
    "palette": "clay"
  },
  "earth elemental": {
    "family": "elemental",
    "size": "large",
    "palette": "slate"
  },
  "water elemental": {
    "family": "slime",
    "size": "large",
    "palette": "mist"
  },
  "lichen": {
    "family": "fungus",
    "size": "small",
    "palette": "sage"
  },
  "brown mold": {
    "family": "fungus",
    "size": "small",
    "palette": "earth"
  },
  "yellow mold": {
    "family": "fungus",
    "size": "small",
    "palette": "amber"
  },
  "green mold": {
    "family": "fungus",
    "size": "small",
    "palette": "sage"
  },
  "red mold": {
    "family": "fungus",
    "size": "small",
    "palette": "clay"
  },
  "shrieker": {
    "family": "fungus",
    "size": "small",
    "palette": "sage"
  },
  "violet fungus": {
    "family": "fungus",
    "size": "small",
    "palette": "plum"
  },
  "gnome": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnome lord": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnome lady": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnome leader": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnomish wizard": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnome king": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnome queen": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "gnome ruler": {
    "family": "humanoid",
    "size": "small",
    "palette": "earth"
  },
  "giant": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "stone giant": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "hill giant": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "fire giant": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "frost giant": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "ettin": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "storm giant": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "titan": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "minotaur": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "jabberwock": {
    "family": "dragon",
    "size": "large",
    "palette": "earth"
  },
  "Keystone Kop": {
    "family": "humanoid",
    "size": "medium",
    "palette": "slate"
  },
  "Kop Sergeant": {
    "family": "humanoid",
    "size": "medium",
    "palette": "slate"
  },
  "Kop Lieutenant": {
    "family": "humanoid",
    "size": "medium",
    "palette": "slate"
  },
  "Kop Kaptain": {
    "family": "humanoid",
    "size": "medium",
    "palette": "slate"
  },
  "lich": {
    "family": "robed",
    "size": "medium",
    "palette": "slate"
  },
  "demilich": {
    "family": "robed",
    "size": "medium",
    "palette": "slate"
  },
  "master lich": {
    "family": "robed",
    "size": "medium",
    "palette": "slate"
  },
  "arch-lich": {
    "family": "robed",
    "size": "medium",
    "palette": "slate"
  },
  "kobold mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "gnome mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "orc mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "dwarf mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "elf mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "human mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "ettin mummy": {
    "family": "mummy",
    "size": "medium",
    "palette": "ivory"
  },
  "giant mummy": {
    "family": "mummy",
    "size": "large",
    "palette": "ivory"
  },
  "red naga hatchling": {
    "family": "naga",
    "size": "small",
    "palette": "clay"
  },
  "black naga hatchling": {
    "family": "naga",
    "size": "small",
    "palette": "ink"
  },
  "golden naga hatchling": {
    "family": "naga",
    "size": "small",
    "palette": "amber"
  },
  "guardian naga hatchling": {
    "family": "naga",
    "size": "small",
    "palette": "sage"
  },
  "red naga": {
    "family": "naga",
    "size": "large",
    "palette": "clay"
  },
  "black naga": {
    "family": "naga",
    "size": "large",
    "palette": "ink"
  },
  "golden naga": {
    "family": "naga",
    "size": "large",
    "palette": "amber"
  },
  "guardian naga": {
    "family": "naga",
    "size": "large",
    "palette": "sage"
  },
  "ogre": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "ogre lord": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "ogre lady": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "ogre leader": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "ogre king": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "ogre queen": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "ogre tyrant": {
    "family": "giant",
    "size": "large",
    "palette": "clay"
  },
  "gray ooze": {
    "family": "slime",
    "size": "medium",
    "palette": "slate"
  },
  "brown pudding": {
    "family": "slime",
    "size": "medium",
    "palette": "earth"
  },
  "green slime": {
    "family": "slime",
    "size": "medium",
    "palette": "sage"
  },
  "black pudding": {
    "family": "slime",
    "size": "medium",
    "palette": "ink"
  },
  "quantum mechanic": {
    "family": "humanoid",
    "size": "medium",
    "palette": "ivory"
  },
  "genetic engineer": {
    "family": "humanoid",
    "size": "medium",
    "palette": "ivory"
  },
  "rust monster": {
    "family": "beetle",
    "size": "medium",
    "palette": "earth"
  },
  "disenchanter": {
    "family": "beetle",
    "size": "medium",
    "palette": "earth"
  },
  "garter snake": {
    "family": "snake",
    "size": "small",
    "palette": "sage"
  },
  "snake": {
    "family": "snake",
    "size": "small",
    "palette": "sage"
  },
  "water moccasin": {
    "family": "snake",
    "size": "small",
    "palette": "sage"
  },
  "python": {
    "family": "snake",
    "size": "small",
    "palette": "sage"
  },
  "pit viper": {
    "family": "snake",
    "size": "small",
    "palette": "sage"
  },
  "cobra": {
    "family": "snake",
    "size": "small",
    "palette": "sage"
  },
  "troll": {
    "family": "giant",
    "size": "large",
    "palette": "sage"
  },
  "ice troll": {
    "family": "giant",
    "size": "large",
    "palette": "sage"
  },
  "rock troll": {
    "family": "giant",
    "size": "large",
    "palette": "sage"
  },
  "water troll": {
    "family": "giant",
    "size": "large",
    "palette": "sage"
  },
  "Olog-hai": {
    "family": "giant",
    "size": "large",
    "palette": "sage"
  },
  "umber hulk": {
    "family": "beetle",
    "size": "large",
    "palette": "earth"
  },
  "vampire": {
    "family": "robed",
    "size": "medium",
    "palette": "clay"
  },
  "vampire lord": {
    "family": "robed",
    "size": "medium",
    "palette": "clay"
  },
  "vampire lady": {
    "family": "robed",
    "size": "medium",
    "palette": "clay"
  },
  "vampire leader": {
    "family": "robed",
    "size": "medium",
    "palette": "clay"
  },
  "Vlad the Impaler": {
    "family": "robed",
    "size": "medium",
    "palette": "clay"
  },
  "barrow wight": {
    "family": "ghost",
    "size": "medium",
    "palette": "slate"
  },
  "wraith": {
    "family": "ghost",
    "size": "medium",
    "palette": "slate"
  },
  "Nazgul": {
    "family": "ghost",
    "size": "medium",
    "palette": "slate"
  },
  "xorn": {
    "family": "tripod",
    "size": "large",
    "palette": "earth"
  },
  "monkey": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "ape": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "owlbear": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "yeti": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "carnivorous ape": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "sasquatch": {
    "family": "ape",
    "size": "large",
    "palette": "earth"
  },
  "kobold zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "gnome zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "orc zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "dwarf zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "elf zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "human zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "ettin zombie": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "ghoul": {
    "family": "shambler",
    "size": "medium",
    "palette": "sage"
  },
  "giant zombie": {
    "family": "shambler",
    "size": "large",
    "palette": "sage"
  },
  "skeleton": {
    "family": "skeleton",
    "size": "medium",
    "palette": "sage"
  },
  "straw golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "paper golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "rope golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "gold golem": {
    "family": "golem",
    "size": "large",
    "palette": "amber"
  },
  "leather golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "wood golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "flesh golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "clay golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "stone golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "glass golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "iron golem": {
    "family": "golem",
    "size": "large",
    "palette": "slate"
  },
  "human": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "elf": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Woodland-elf": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Green-elf": {
    "family": "humanoid",
    "size": "medium",
    "palette": "sage"
  },
  "Grey-elf": {
    "family": "humanoid",
    "size": "medium",
    "palette": "slate"
  },
  "elf-lord": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "elf-lady": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "elf-noble": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Elvenking": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Elvenqueen": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "elven monarch": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "doppelganger": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "shopkeeper": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "guard": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "prisoner": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Oracle": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "priest": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "priestess": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "aligned cleric": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "high priest": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "high priestess": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "high cleric": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "soldier": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "sergeant": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "nurse": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "lieutenant": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "captain": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "watchman": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "watch captain": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Medusa": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Wizard of Yendor": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Croesus": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "ghost": {
    "family": "ghost",
    "size": "medium",
    "palette": "mist"
  },
  "shade": {
    "family": "ghost",
    "size": "medium",
    "palette": "mist"
  },
  "water demon": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "incubus": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "succubus": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "amorous demon": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "horned devil": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "erinys": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "barbed devil": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "marilith": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "vrock": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "hezrou": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "bone devil": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "ice devil": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "nalfeshnee": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "pit fiend": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "sandestin": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "balrog": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Juiblex": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Yeenoghu": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Orcus": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Geryon": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Dispater": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Baalzebub": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Asmodeus": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Demogorgon": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Death": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Pestilence": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Famine": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "mail daemon": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "djinni": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "jellyfish": {
    "family": "jellyfish",
    "size": "medium",
    "palette": "mist"
  },
  "piranha": {
    "family": "fish",
    "size": "medium",
    "palette": "mist"
  },
  "shark": {
    "family": "fish",
    "size": "medium",
    "palette": "mist"
  },
  "giant eel": {
    "family": "snake",
    "size": "large",
    "palette": "mist"
  },
  "electric eel": {
    "family": "snake",
    "size": "medium",
    "palette": "mist"
  },
  "kraken": {
    "family": "tentacled",
    "size": "large",
    "palette": "mist"
  },
  "newt": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "gecko": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "iguana": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "baby crocodile": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "lizard": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "chameleon": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "crocodile": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "salamander": {
    "family": "lizard",
    "size": "small",
    "palette": "sage"
  },
  "long worm tail": {
    "family": "worm",
    "size": "small",
    "palette": "earth"
  },
  "archeologist": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "barbarian": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "caveman": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "cavewoman": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "cave dweller": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "healer": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "knight": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "monk": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "cleric": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "ranger": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "rogue": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "samurai": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "tourist": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "valkyrie": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "wizard": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Lord Carnarvon": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Pelias": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Shaman Karnov": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Hippocrates": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "King Arthur": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Grand Master": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Arch Priest": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Orion": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Master of Thieves": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Lord Sato": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Twoflower": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Norn": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Neferet the Green": {
    "family": "humanoid",
    "size": "medium",
    "palette": "sage"
  },
  "Minion of Huhetotl": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Thoth Amon": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Chromatic Dragon": {
    "family": "dragon",
    "size": "large",
    "palette": "sage"
  },
  "Cyclops": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "Ixoth": {
    "family": "dragon",
    "size": "large",
    "palette": "sage"
  },
  "Master Kaen": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Nalzok": {
    "family": "demon",
    "size": "large",
    "palette": "clay"
  },
  "Scorpius": {
    "family": "scorpion",
    "size": "small",
    "palette": "earth"
  },
  "Master Assassin": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Ashikaga Takauji": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "Lord Surtur": {
    "family": "giant",
    "size": "large",
    "palette": "earth"
  },
  "Dark One": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "student": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "chieftain": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "neanderthal": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "attendant": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "page": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "abbot": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "acolyte": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "hunter": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "thug": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "ninja": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "roshi": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "guide": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "warrior": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  },
  "apprentice": {
    "family": "humanoid",
    "size": "medium",
    "palette": "earth"
  }
};
