import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createTestHarness,MemoryStorage,publicStoreFor} from './server.mjs';
import {storageContext} from '../src/storage.ts';
import {publicReplayContext} from '../src/public-replay-store.ts';
import {markRecorded} from '../src/ledger-store.ts';
import {chromium} from '../../../web/neohack.dev/node_modules/playwright-core/index.mjs';

test('ledger replay availability comes from public recordings and reaches outside the top 100',async t=>{
 const store=new MemoryStorage();
 const runs=Array.from({length:102},(_,i)=>({id:'run-'+i,name:'Hero '+i,role:'wizard',turn:200-i,maxLevel:1,ended:false,updatedAt:100,replayAvailable:true}));
 await store.write('board/index.json',{runs,errors:[{day:new Date().toISOString().slice(0,10),code:'engine',count:7,last:Date.now(),build:''}]});
 await store.write('replays/run-101.json',{frames:['objects/frame.json'],revision:1});
 await store.write('accounts/private-recording.json',{runId:'run-0',frames:['private']});
 await storageContext.run(store,()=>publicReplayContext.run(publicStoreFor(store),()=>markRecorded('run-101')));
 let listings=0;const list=store.list.bind(store);store.list=async prefix=>{listings++;return list(prefix);};
 const server=createTestHarness({store});const{url}=await server.listen();t.after(()=>server.close());
 const stats=await(await fetch(new URL('/api/stats',url))).json();
 assert.equal(stats.totals.runs,102);assert.equal(stats.recent.length,102);
 assert.ok(stats.recent.filter(r=>r.id!=='run-101').every(r=>r.replayAvailable===false),'client-provided claims and private recordings do not enable public playback');
 assert.deepEqual(stats.best.map(r=>r.id),['run-101'],'only a public recording ranks');assert.equal(stats.best[0].replayAvailable,true);
 assert.deepEqual(stats.recorded.map(r=>r.id),['run-101']);assert.equal(stats.recorded[0].replayAvailable,true);
 await fetch(new URL('/api/stats',url));assert.equal(listings,0,'refresh reads bounded summaries, never recording files or listings');
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM??'/usr/bin/chromium',headless:true,chromiumSandbox:true});t.after(()=>browser.close());
 const page=await browser.newPage();await page.goto(new URL('/dashboard',url).href);
 await page.waitForFunction(()=>document.querySelectorAll('#runs tr').length===1);
 assert.equal(await page.locator('#runs .run-replay').count(),1);
 assert.equal(await page.locator('#runs [aria-label="No public recording"]').count(),0);
 await page.locator('.plot-data summary').click();assert.equal(await page.locator('#recent-runs tr').count(),102,'unrecorded runs stay listed among recent runs');await page.locator('.plot-data summary').click();
 assert.equal(await page.locator('#error-summary, #dungeon-health').count(),0);
 const row=await page.locator('#runs tr').first().boundingBox();assert.ok(row.height<65,'rows stay compact');
 await page.locator('#status').selectOption('recorded');
 assert.equal(await page.locator('#runs tr').count(),1);
 assert.equal(await page.getByRole('link',{name:'Show replay for Hero 101',exact:true}).getAttribute('href'),new URL('/replays/run-101',url).href);
 assert.match(await page.locator('#leaders-description').textContent(),/adventures with replays/);
});
