import {createServer} from 'node:http';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createTestHarness} from './server.mjs';
import {chromium} from '../../../web/neohack.dev/node_modules/playwright-core/index.mjs';

test('real cloud run records public scenes, embeds after death and shares a ledger lightbox', {timeout:120000}, async t=>{
  const server=createTestHarness();const {url}=await server.listen();
  const browser=await chromium.launch({executablePath:process.env.CHROMIUM??'/usr/bin/chromium',headless:true,chromiumSandbox:true});
  t.after(async()=>{await browser.close();await server.close();});
  const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await fetch(new URL("/api/stats",url)); // Prime an empty availability cache before recording.
  await page.goto(String(url));
  await page.waitForFunction(()=>!document.querySelector('#new-adventure').disabled);
  await page.getByRole('button',{name:'Begin your adventure',exact:true}).click();
  await page.getByLabel('YOUR NAME',{exact:true}).fill('Replay Ada');
  await page.locator('input[name=role][value=valkyrie]').check();
  await page.getByText('Choose a world seed (optional)',{exact:true}).click();
  await page.getByLabel('A number for a repeatable starting world').fill('9');
  await page.getByRole('button',{name:'Enter the dungeon →',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('pixel-nethack').snapshot?.observation && document.querySelector('pixel-nethack').getAttribute('aria-busy')==='false');
  // Close the first witnessed passage before operating the game menu.
  await page.keyboard.press('Escape');
  await page.evaluate(async()=>{const a=document.querySelector('pixel-nethack');for(let i=0;i<28;i++)await a.run(()=>a.game.wait());await a.publicRecorder.flush();});
  const state=await page.evaluate(()=>document.querySelector('pixel-nethack').snapshot);
  const endpoint=new URL('/api/runs/'+state.sessionId+'/replay',url);
  let response=await fetch(endpoint);assert.equal(response.status,200);
  const first=await response.json();assert.equal(first.frames.length,25);assert.equal(first.next,25);
  const ledger=await (await fetch(new URL("/api/stats",url))).json();
  assert.equal(ledger.recorded.find(run=>run.id===state.sessionId)?.replayAvailable,true,"a first committed frame invalidates the empty availability cache");
  assert.equal(response.headers.get('access-control-allow-origin'),'*');
  const second=await (await fetch(new URL('?offset=25',endpoint))).json();
  const expected=structuredClone(state.observation);delete expected.neighborhood;
  assert.deepEqual(second.frames.at(-1).observation,expected,'the public recording preserves canonical perceived information');
  assert.deepEqual(second.frames.at(-1).decision,state.decision);
  assert.deepEqual(second.frames.at(-1).outcome,state.outcome);
  assert.ok(!('storage' in first.frames[0]));assert.ok(!('recording' in first.frames[0]));
  assert.ok(!JSON.stringify(first).includes('vault'));
  assert.equal((await fetch(endpoint,{method:'PUT',headers:{'content-type':'application/json'},body:'{}'})).status,401);
  const privateBookmark=page.url();
  const vault=new URLSearchParams(new URL(privateBookmark).hash.slice(1)).get('vault');
  const append=(body,token=vault)=>fetch(endpoint,{method:'PUT',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify(body)});
  assert.equal((await append({index:0,frame:first.frames[0]})).status,409,'duplicate frame cannot rewrite the recording');
  assert.equal((await append({index:first.count,frame:{...state,sessionId:'another-run'}})).status,400);
  assert.equal((await append({index:first.count,frame:state},crypto.randomUUID())).status,403);
  assert.equal((await fetch(new URL('?offset=-1',endpoint))).status,400);
  const afterDenied=await (await fetch(endpoint)).json();assert.equal(afterDenied.count,first.count);
  await page.getByLabel('Game menu',{exact:true}).click();
  const summary=await page.getByLabel('Game menu',{exact:true}).boundingBox();const menu=await page.locator('.hud-menu-body').boundingBox();
  assert.ok(menu.y>=summary.y+summary.height && Math.abs(menu.x+menu.width-summary.x-summary.width)<2);
  await page.locator('#copy-embed').click();
  const embed=await page.evaluate(()=>navigator.clipboard.readText());assert.ok(embed.includes('autoplay speed="4" controls'));assert.ok(embed.includes(state.sessionId));assert.ok(!embed.includes('vault'));
  await page.getByRole('button',{name:'Abandon run',exact:true}).click();
  await page.getByRole('button',{name:'Yes, continue',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#death-replay neohack-world')?.snapshot);
  await page.locator('#death-copy-link').click();
  const link=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(new URL(link).searchParams.get('run'),state.sessionId);assert.ok(!link.includes('#'));
  await page.screenshot({path:'/tmp/neohack-replay-death.png',fullPage:true});
  let releasePage;const heldPage=new Promise(resolve=>{releasePage=resolve;});
  await page.route('**/api/runs/*/replay?offset=25',async route=>{await heldPage;await route.continue();});
  await page.goto(link);
  await page.waitForFunction(()=>document.querySelector('neohack-world')?.shadowRoot.querySelector('#status').textContent.includes('frames received'));
  await page.evaluate(()=>document.querySelector('neohack-world').setAttribute('role','wizard'));
  assert.match(await page.locator('neohack-world').locator('#status').textContent(),/Loading replay/);
  assert.equal(await page.locator('neohack-world').locator('#progress').textContent(),'Loading…');
  releasePage();

  await page.waitForFunction(()=>document.querySelector('#replay-lightbox').open && document.querySelector('neohack-world')?.snapshot);
  const world=page.locator('neohack-world');
  await world.getByRole('button',{name:'Pause replay',exact:true}).click();
  await world.getByLabel('Replay frame',{exact:true}).fill('0');
  assert.equal(await world.getByLabel('Playback speed',{exact:true}).inputValue(),'4');
  await world.getByLabel('Playback speed',{exact:true}).selectOption('1');
  await world.getByRole('button',{name:'Play replay',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('neohack-world').snapshot.revision>0);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/neohack-replay-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('neohack-world'));
  await page.goto(new URL('/dashboard?run=missing-recording',url).href);
  await page.waitForFunction(()=>document.querySelector('neohack-world')?.shadowRoot.textContent.includes('Replay unavailable'));
  // A new visit can append to an existing public recording without rewriting it.
  await page.goto(privateBookmark);
  await page.waitForFunction(()=>document.querySelector('pixel-nethack').snapshot?.ended);
  await page.evaluate(()=>document.querySelector('pixel-nethack').publicRecorder.flush());
  const embedServer=createServer((req,res)=>{res.setHeader('content-type','text/html');res.end('<script type="module" src="'+url+'component/neohack.js"></script><neohack-world src="'+link+'" controls autoplay="false" speed="2" sound style="height:420px"></neohack-world>');});
  await new Promise(resolve=>embedServer.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>embedServer.close(resolve)));
  await page.goto('http://127.0.0.1:'+embedServer.address().port);
  await page.waitForFunction(()=>document.querySelector('neohack-world')?.snapshot);
  const external=page.locator('neohack-world');
  assert.equal(await external.getByRole('button',{name:'Play replay',exact:true}).count(),1);
  const soundRequest=page.waitForRequest(r=>r.url()===new URL('/audio/footstep00.ogg',url).href);
  await external.getByRole('button',{name:'Play replay',exact:true}).click();await soundRequest;
  await page.waitForFunction(()=>document.querySelector('neohack-world').shadowRoot.querySelector('#sound').getAttribute('aria-pressed')==='true');
  await external.getByRole('button',{name:'Pause replay',exact:true}).click();
  await page.evaluate(()=>{const w=document.querySelector('neohack-world');w.seek(w.frames.length-1);w.setAttribute('loop','');w.play(50);});
  await page.waitForFunction(()=>Number(document.querySelector('neohack-world').shadowRoot.querySelector('#seek').value)<5);
  await page.evaluate(()=>{window.detachedWorld=document.querySelector('neohack-world');window.detachedWorld.remove();});
  const stopped=await page.evaluate(()=>window.detachedWorld.snapshot.revision);
  await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.detachedWorld.snapshot.revision),stopped);
  assert.deepEqual(errors,[]);
});
