import {inputRecords} from '../../../lib/neonethack/wasm/protocol-reader.mjs';
import {WasmTransport} from '../../../lib/neonethack/dist/typescript/wasm.js';
import {gzipSync,gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createTestHarness} from './server.mjs';
import {chromium} from '../../../web/neohack.dev/node_modules/playwright-core/index.mjs';

test('real cloud run reconstructs public scenes, embeds after death and forwards ledger links to the run\'s page', {timeout:120000}, async t=>{
  const server=createTestHarness();const {url}=await server.listen();
  const browser=await chromium.launch({executablePath:process.env.CHROMIUM??'/usr/bin/chromium',headless:true,chromiumSandbox:true});
  t.after(async()=>{await browser.close();await server.close();});
  const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await fetch(new URL("/api/stats",url)); // Prime an empty availability cache before recording.
  await page.goto(String(url));
  await page.waitForFunction(()=>!document.querySelector('#new-adventure').disabled);
  await page.getByRole('button',{name:'Begin your adventure',exact:true}).click();
  await page.getByLabel('YOUR NAME',{exact:true}).fill('Replay Ada');
  await page.locator('input[name=role][value=valkyrie]').check();
  await page.getByText('Choose a world seed (optional)',{exact:true}).click();
  await page.getByLabel('A number for a repeatable starting world').fill('9');
  await page.getByRole('button',{name:'Enter the dungeon →',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('pixel-nethack').snapshot?.observation && document.querySelector('pixel-nethack').getAttribute('aria-busy')==='false');
  // Close the first witnessed passage before operating the game menu.
  await page.keyboard.press('Escape');
  await page.evaluate(async()=>{const a=document.querySelector('pixel-nethack');for(let i=0;i<28;i++)await a.run(()=>a.game.wait());await a.publicRecorder.flush();});
  const state=await page.evaluate(()=>document.querySelector('pixel-nethack').snapshot);
  const endpoint=new URL('/api/runs/'+state.sessionId+'/replay',url);
  let response=await fetch(endpoint,{redirect:'manual'});assert.equal(response.status,302);
  assert.equal(response.headers.get('access-control-allow-origin'),'*');
  const manifestURL=new URL(response.headers.get('location'),endpoint);
  const manifest=await (await fetch(manifestURL)).json();
  assert.ok(manifest.count>=25);
  const frames=[];
  const replay=await WasmTransport.create();try{for await(const record of inputRecords(manifest,manifestURL))frames.push(await replay.playback(record));}finally{await replay.close();}
  assert.equal(frames.length,manifest.count);
  const ledger=await (await fetch(new URL("/api/stats",url))).json();
  assert.equal(ledger.recorded.find(run=>run.id===state.sessionId)?.replayAvailable,true,"a first committed frame invalidates the empty availability cache");
  const expected=structuredClone(state.observation);
  assert.deepEqual(frames.at(-1).observation,expected,'the public recording preserves canonical perceived information');
  assert.deepEqual(frames.at(-1).decision,state.decision);
  assert.deepEqual(frames.at(-1).outcome,state.outcome);
  assert.equal(manifest.format,'neonethack.inputs');
  assert.ok(!JSON.stringify(frames).includes('vault'));
  const privateBookmark=page.url(),vault=new URLSearchParams(new URL(privateBookmark).hash.slice(1)).get('vault');
  const firstBytes=Buffer.from(await(await fetch(new URL(manifest.chunks[0].path,manifestURL))).arrayBuffer());
  assert.ok(!gunzipSync(firstBytes).toString().includes(vault),'upload capability is absent from public input bytes');
  const append=(bytes,token=vault)=>fetch(new URL('/api/runs/'+state.sessionId+'/inputs',url),{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'application/gzip','x-content-sha256':createHash('sha256').update(bytes).digest('hex')},body:bytes});
  assert.equal((await append(firstBytes)).status,200,'exact retry does not append twice');
  const changed=JSON.parse(gunzipSync(firstBytes));changed.records[0].request.params.seed++;
  assert.equal((await append(gzipSync(JSON.stringify(changed)))).status,409,'a changed duplicate cannot rewrite a committed range');
  assert.equal((await append(firstBytes,crypto.randomUUID())).status,403);
  assert.equal((await(await fetch(manifestURL)).json()).count,manifest.count);
  await page.getByLabel('Game menu',{exact:true}).click();
  const summary=await page.getByLabel('Game menu',{exact:true}).boundingBox();const menu=await page.locator('.hud-menu-body').boundingBox();
  assert.ok(menu.y>=summary.y+summary.height && Math.abs(menu.x+menu.width-summary.x-summary.width)<2);
  await page.locator('#copy-embed').click();
  await page.waitForFunction(()=>document.querySelector('#copy-embed').textContent==='Embed copied');
  const embed=await page.evaluate(()=>navigator.clipboard.readText());assert.ok(embed.includes('autoplay speed="4" controls'));assert.ok(embed.includes(state.sessionId));assert.ok(!embed.includes('vault'));
  await page.getByRole('button',{name:'Abandon run',exact:true}).click();
  await page.getByRole('button',{name:'Yes, continue',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#death-replay neohack-world')?.snapshot);
  await page.locator('#death-copy-link').click();
  const link=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(new URL(link).pathname,'/replays/'+state.sessionId);assert.ok(!link.includes('#'));
  await page.screenshot({path:'/tmp/neohack-replay-death.png',fullPage:true});
  let releasePage;const heldPage=new Promise(resolve=>{releasePage=resolve;});
  t.after(()=>releasePage());
  let chunkRequests=0;
  await page.goto(link);
  await page.waitForFunction(()=>document.querySelector('#replay')?.snapshot);
  assert.equal(await page.locator('#share-url').inputValue(),link);
  await page.route('**/replay-files/replays/*/chunks/*.gz',async route=>{if(++chunkRequests===2)await heldPage;await route.continue();});
  // Ledger links to a run land on its own page; the old dashboard address forwards there.
  await page.goto(new URL('/dashboard?run='+state.sessionId,url).href);
  await page.waitForURL(u=>u.pathname==='/replays/'+state.sessionId);
  await page.waitForFunction(()=>document.querySelector('#replay')?.snapshot);
  await page.evaluate(()=>document.querySelector('neohack-world').setAttribute('role','wizard'));
  assert.match(await page.locator('neohack-world').locator('#status').textContent(),/Turn/);
  assert.match(await page.locator('neohack-world').locator('#progress').textContent(),/actions/);
  releasePage();

  await page.waitForFunction(()=>document.querySelector('neohack-world')?.snapshot);
  const world=page.locator('neohack-world');
  await world.getByRole('button',{name:'Play replay',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('neohack-world')?.snapshot?.revision>=2);
  await world.getByRole('button',{name:'Pause replay',exact:true}).click();
  await world.getByLabel('Replay frame',{exact:true}).fill('0');
  assert.equal(await world.getByLabel('Playback speed',{exact:true}).inputValue(),'4');
  await world.getByLabel('Playback speed',{exact:true}).selectOption('1');
  await world.getByRole('button',{name:'Play replay',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('neohack-world').snapshot.revision>0);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/neohack-replay-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.goto(new URL('/dashboard?run=missing-recording',url).href);
  await page.waitForURL(u=>u.pathname==='/replays/missing-recording');
  await page.waitForFunction(()=>document.querySelector('neohack-world')?.shadowRoot.textContent.includes('Replay unavailable'));
  // A new visit can append to an existing public recording without rewriting it.
  await page.goto(privateBookmark);
  await page.waitForFunction(()=>document.querySelector('pixel-nethack').snapshot?.ended);
  await page.evaluate(()=>document.querySelector('pixel-nethack').publicRecorder.flush());
  const embedServer=createServer((req,res)=>{res.setHeader('content-type','text/html');res.end('<script type="module" src="'+url+'component/neohack.js"></script><neohack-world src="'+link+'" controls autoplay="false" speed="2" sound style="height:420px"></neohack-world>');});
  await new Promise(resolve=>embedServer.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>embedServer.close(resolve)));
  await page.goto('http://127.0.0.1:'+embedServer.address().port);
  await page.waitForFunction(()=>document.querySelector('neohack-world')?.snapshot);
  const external=page.locator('neohack-world');
  assert.equal(await external.getByRole('button',{name:'Play replay',exact:true}).count(),1);
  const soundRequest=page.waitForRequest(r=>r.url()===new URL('/audio/footstep00.ogg',url).href);
  await external.getByRole('button',{name:'Play replay',exact:true}).click();await soundRequest;
  await page.waitForFunction(()=>document.querySelector('neohack-world').shadowRoot.querySelector('#sound').getAttribute('aria-pressed')==='true');
  await external.getByRole('button',{name:'Pause replay',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('neohack-world').sourcePending);
  await page.evaluate(async()=>{const w=document.querySelector('neohack-world');await w.seek(w.sourceTotal-1);w.setAttribute('loop','');w.play(50);});
  await page.waitForFunction(()=>Number(document.querySelector('neohack-world').shadowRoot.querySelector('#seek').value)<5);
  await page.evaluate(()=>{window.detachedWorld=document.querySelector('neohack-world');window.detachedWorld.remove();});
  const stopped=await page.evaluate(()=>window.detachedWorld.snapshot.revision);
  await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.detachedWorld.snapshot.revision),stopped);
  assert.deepEqual(errors,[]);
});
