import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './native-fixture.mjs';
const here = game => game.observation.neighborhood.cells.find(c => !c.dx && !c.dy);

test('C availability knows empty candidates and drinking underfoot preserves fountain consent', async t => {
  const { api } = await fixture(t);
  let game = await api.create({name:'Water',seed:3,role:'valkyrie',race:'human',gender:'female',align:'lawful'});
  const id = game.id;
  const before = game.state;
  assert.equal(here(game).actions.find(a => a.key === 'drink').availability, 'knownBlocked');
  assert.equal(here(game).actions.find(a => a.key === 'zap').availability, 'knownBlocked');
  assert.equal(here(game).actions.find(a => a.key === 'eat').availability, 'needsSelection');
  const free = await game.actions('here');
  assert.equal(free.cell.actions.find(a => a.key === 'drink').availability, 'knownBlocked');
  assert.equal(game.state.revision, before.revision);
  const fountain = game.observation.world.find(c => c.terrain.type === 'fountain');
  assert.equal(fountain.x, game.observation.you.x - 1);
  assert.equal(fountain.y, game.observation.you.y);
  await game.move('west');
  assert.equal(here(game).terrain.type, 'fountain');
  assert.equal(here(game).actions.find(a => a.key === 'drink').availability, 'attemptable');
  let offer = await game.drink();
  assert.equal(offer.error, undefined);
  assert.equal(offer.decision?.kind, 'confirmation');
  assert.match(offer.decision.about, /fountain/i);
  const turn = game.observation.turn;
  await game.close();
  game = await api.resume(id);
  assert.deepEqual(game.decision, offer.decision);
  const declined = await game.answer(game.decision.id, {kind:'confirmation',confirm:false});
  assert.equal(declined.error, undefined);
  assert.equal(declined.observation.turn, turn);
  offer = await game.drink();
  const drank = await game.answer(offer.decision.id, {kind:'confirmation',confirm:true});
  assert.equal(drank.error, undefined);
  assert.equal(drank.observation.turn, turn + 1);
});
