import {test} from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {instrumentedNativeEngine} from './instrumented-native-engine.mjs';
import {fixture, identity} from './native-fixture.mjs';
test('isolated high altar: floor consent, bound Amulet selection, genuine ascension and durable terminal receipt',async t=>{
  const enginePath=await instrumentedNativeEngine(t,resolve(import.meta.dirname,'offer-fixture.inc'),'offer_fixture');
  const a=await fixture(t,{enginePath});
  let game=await a.api.create(identity);
  const amulet=game.observation.inventory.find(i=>i.category==='amulet');assert.ok(amulet);
  const floor=await game.offer();
  assert.equal(floor.decision?.kind,'confirmation');
  assert.match(floor.decision.about,/lichen corpse/);
  await game.close(); game=await a.api.resume(game.id);
  assert.equal(game.decision.id,floor.decision.id);
  const items=await game.answer(game.decision.id,{kind:'confirmation',confirm:false});
  assert.equal(items.decision?.kind,'item');
  assert.ok(items.decision.options.some(i=>i.id===amulet.id));
  await game.close(); game=await a.api.resume(game.id);
  assert.equal(game.decision.id,items.decision.id);
  const request={version:1,method:'decision.answer',params:{sessionId:game.id,requestId:'final-offering',expectedRevision:game.state.revision,decisionId:game.decision.id,answer:{kind:'item',item:{id:amulet.id}}}};
  const result=await a.transport.send(request);
  assert.equal(result.error,undefined);
  assert.equal(result.ended,true);
  assert.equal(result.end.kind,'ascended');
  assert.ok(Number.isSafeInteger(result.end.score) && result.end.score >= 0);
  assert.equal(result.decision,null);
  assert.deepEqual(await a.transport.send(request),result);
  await a.transport.close();
  const b=await fixture(t,{sessions:a.sessions});
  const resumed=await b.api.resume(game.id);
  assert.deepEqual(resumed.state.end,result.end);
  assert.deepEqual(await b.transport.send(request),result);
});
