// Generated by scripts/generate.ts; do not edit.
export type EquipmentSlot = "bodyArmor" | "cloak" | "helmet" | "shield" | "gloves" | "boots" | "shirt" | "amulet" | "leftRing" | "rightRing" | "eyewear" | "weapon" | "offhand" | "alternateWeapon" | "quiver" | "skin" | "ball" | "chain";
