// Generated by scripts/generate.ts; do not edit.
export interface MethodParams {
  "protocol.describe": {  };
  "session.create": { name?: string; seed?: number; role?: "archeologist" | "barbarian" | "caveman" | "healer" | "knight" | "monk" | "priest" | "rogue" | "ranger" | "samurai" | "tourist" | "valkyrie" | "wizard"; race?: "human" | "elf" | "dwarf" | "gnome" | "orc"; gender?: "male" | "female"; align?: "lawful" | "neutral" | "chaotic"; automaticPickup?: { enabled: boolean; itemTypes: ReadonlyArray<"gold" | "food" | "potions" | "scrolls" | "weapons" | "armor" | "rings" | "amulets" | "tools" | "spellbooks" | "wands" | "gems" | "rocks" | "balls" | "chains">; arrows: boolean; leaveCorpses: boolean; leaveKnownCursed: boolean } };
  "session.observe": { sessionId: string };
  "session.actions": { sessionId: string; expectedRevision: number; target: "here" | { direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" } };
  "session.resume": { sessionId: string };
  "session.close": { sessionId: string };
  "game.move": { sessionId: string; requestId: string; expectedRevision: number; direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" };
  "game.wait": { sessionId: string; requestId: string; expectedRevision: number };
  "game.climb": { sessionId: string; requestId: string; expectedRevision: number; direction: "up" | "down" };
  "game.search": { sessionId: string; requestId: string; expectedRevision: number };
  "game.kick": { sessionId: string; requestId: string; expectedRevision: number; target?: { direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" } };
  "game.open": { sessionId: string; requestId: string; expectedRevision: number; target?: { direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" } };
  "game.close": { sessionId: string; requestId: string; expectedRevision: number; target?: { direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" } };
  "game.pickup": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.eat": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.drink": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.wield": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.equip": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.remove": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.read": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.apply": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.drop": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string } };
  "game.zap": { sessionId: string; requestId: string; expectedRevision: number; item?: string | { id: string }; target?: "self" | { direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" | "up" | "down" } };
  "game.loot": { sessionId: string; requestId: string; expectedRevision: number };
  "game.configurePickup": { sessionId: string; requestId: string; expectedRevision: number; automaticPickup: { enabled: boolean; itemTypes: ReadonlyArray<"gold" | "food" | "potions" | "scrolls" | "weapons" | "armor" | "rings" | "amulets" | "tools" | "spellbooks" | "wands" | "gems" | "rocks" | "balls" | "chains">; arrows: boolean; leaveCorpses: boolean; leaveKnownCursed: boolean } };
  "game.quit": { sessionId: string; requestId: string; expectedRevision: number };
  "game.pray": { sessionId: string; requestId: string; expectedRevision: number };
  "decision.answer": { sessionId: string; requestId: string; expectedRevision: number; decisionId: string; answer: { kind: "position"; position: { x: number; y: number } | "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" | "finish" | "help" } | { kind: "item"; item: string | { id: string } } | { kind: "target"; target: "self" | { direction: "north" | "northeast" | "east" | "southeast" | "south" | "southwest" | "west" | "northwest" | "up" | "down" } } | { kind: "confirmation"; confirm: boolean } | { kind: "choice"; choose: ReadonlyArray<number> } | { kind: "text"; text: string } };
  "decision.cancel": { sessionId: string; requestId: string; expectedRevision: number; decisionId: string };
}
export type Method = keyof MethodParams;
export type Request<M extends Method = Method> = { [K in M]: { version: 1; method: K; params: MethodParams[K] } }[M];
