// Generated by scripts/generate.ts; do not edit.
export type HungerState = "satiated" | "not_hungry" | "hungry" | "weak" | "fainting" | "fainted" | "starved" | "unknown";
export type BurdenState = "unencumbered" | "burdened" | "stressed" | "strained" | "overtaxed" | "overloaded" | "unknown";
